### ISSUE TITLE
Laravel 5.3 support?

### ISSUE THREAD

**Issue by cjmaxik** [gggordon/laravel-disqus-sso#1]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.3.1
    - Conclusion: don't install laravel/framework v5.3.1
    - modbase/disqus-sso 1.1.2 requires illuminate/support 5.2.\* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.6, v5.2.7].
    - modbase/disqus-sso 1.1.1 requires illuminate/support 5.2.\* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.6, v5.2.7].
    - modbase/disqus-sso 1.1.0 requires illuminate/support 5.2.\* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.3.1
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.3.1
    - Installation request for laravel/framework (locked at v5.3.1, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.1].
    - Installation request for modbase/disqus-sso ^1.1 -> satisfiable by modbase/disqus-sso[1.1.2, 1.1.1, 1.1.0].`

**Comment by gggordon** [comment]
I just included an update and and local tests were successful. Additional tests are included on [Travis CI](https://travis-ci.org/gggordon/laravel-disqus-sso) .

Be sure to update your `composer.json` file to utilize the "support-5.2" of this repository

```
    "repositories":{
        ...
        {
            "type":"git",
            "url":"https://github.com/gggordon/laravel-disqus.git"
        }
        ...
    },
```
